version: '3.8'

services:
  db:
    image: postgres:17.4
    env_file:
      - ./.envs/.production/.postgres
    # ports:
    #   - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  web:
    build: 
      context: .
      dockerfile: ./compose/production/Dockerfile
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always 
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres


volumes:
  postgres_data:
